/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Subs;

import javax.swing.*;        
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SubGUI extends javax.swing.JFrame {

    /**
     * Creates new form SubGUI
     */
    public SubGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameT = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        typeS = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        sizeS = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        breadS = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        beverageS = new javax.swing.JList<>();
        quantityS = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        zipT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lba = new javax.swing.JLabel();
        phoneN = new javax.swing.JFormattedTextField();
        importF = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        orderImport = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fred's Famous Subs");

        jLabel1.setText("Welcome to Fred's Famous Subs!");

        jLabel2.setText("Name");

        jLabel3.setText("Street #");

        jLabel4.setText("Please complete the following information to submit an order:");

        nameT.setToolTipText("Enter your full name");
        nameT.setFocusTraversalPolicyProvider(true);

        address.setToolTipText("Enter your full address");

        typeS.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Meatball Sub", "Veggie Sub", "Turkey Sub" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        typeS.setToolTipText("Select the sandwich type you would like");
        jScrollPane1.setViewportView(typeS);

        sizeS.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "6 Inch", "12 Inch" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sizeS.setToolTipText("Select the size you would like");
        jScrollPane2.setViewportView(sizeS);

        breadS.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Parmesean Bread", "White Bread" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        breadS.setToolTipText("Select the bread you would like on your sandwich");
        jScrollPane3.setViewportView(breadS);

        beverageS.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Coffee", "Soda", "Tea", "Water" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        beverageS.setToolTipText("Select the beverage you would like");
        jScrollPane4.setViewportView(beverageS);

        quantityS.setMaximum(10);
        quantityS.setMinimum(1);
        quantityS.setMinorTickSpacing(1);
        quantityS.setPaintLabels(true);
        quantityS.setPaintTicks(true);
        quantityS.setSnapToTicks(true);
        quantityS.setToolTipText("Drag the slider to the right to increase quantity desired");
        quantityS.setValue(1);
        quantityS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setText("Sandwich Type");

        jLabel6.setText("Size");

        jLabel7.setText("Bread Type");

        jLabel8.setText("Beverage");

        jLabel9.setText("Quantity");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        submit.setText("Submit!");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel11.setText("Phone #");

        city.setToolTipText("Enter your city of residence");

        jLabel12.setText("City");

        jLabel13.setText("State");

        state.setToolTipText("Enter your state of residence");

        zipT.setToolTipText("Enter your ZIP Code");

        jLabel14.setText("Zip");

        phoneN.setToolTipText("Enter your phone number");

        importF.setText("Import!");
        importF.setToolTipText("Import a previously made order");
        importF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importFActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(orderImport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quantityS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(submit)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7)
                                                        .addGap(74, 74, 74)
                                                        .addComponent(jLabel8))
                                                    .addComponent(jLabel9)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(importF))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel11))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(city, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(nameT)
                                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                            .addComponent(phoneN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 91, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lba)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(zipT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phoneN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quantityS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(importF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        // initialize variables for button press, get text from boxes 
        
        String type = "";
        String size = "";
        String bread = "";
        String beverage = "";
        String name = "";
        String addressBox = "";
        String zip = "";
        int quantity;
     
            try{
            name = nameT.getText(); //get text from Name field
            if ( nameT.getText() == ""){
                JOptionPane.showMessageDialog(null, "Please enter your name", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for name
            }
            quantity = quantityS.getValue(); // get quantity from slider
            
            addressBox = address.getText()+ " " + city.getText() + " " + state.getText(); //get text from address, city, state, and zip fields
            if(address.getText() == ""){
                JOptionPane.showMessageDialog(null, "Please enter your street address and city", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for street number
            }
            if(city.getText() == ""){
                JOptionPane.showMessageDialog(null, "Please enter your city", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for city
            }
            if(state.getText() == ""){
                JOptionPane.showMessageDialog(null, "Please enter your ZIP code", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for state of residence
            }
            size = sizeS.getSelectedValue(); //get value from size list
            if (size == null){
                JOptionPane.showMessageDialog(null, "Please select a size", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for size
            }
            type = typeS.getSelectedValue(); //get value from type list
            if (type == null){
                JOptionPane.showMessageDialog(null, "Please select a type", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for type
            }
            bread = breadS.getSelectedValue(); //get value from bread list
            if (breadS == null){
                JOptionPane.showMessageDialog(null, "Please select a bread for your sandwich", "Invalid Field", JOptionPane.INFORMATION_MESSAGE); // display message asking for bread type
            }
           beverage = beverageS.getSelectedValue();  //get drink from drink list
           
           zip = zipT.getText(); //get text from ZIP field
           int zp;
           zp = Integer.parseInt(zip); //parse zip string to int
                
                String phone =  phoneN.getText();
                 int phn;
            phn = Integer.parseInt(phone); //parse phone string to int
            
            
            StringBuilder str1 = new StringBuilder( "Hello " + name + "\n" + "Your order is: x" + quantity + " " + size + " " + type + " " + bread + " with a "  + beverage + "\n" + "It will be delivered to " + addressBox + " "+ zp + "\nIf we encounter any issues we will call " + phn );
            JOptionPane.showMessageDialog(null, str1, "Final Order", JOptionPane.INFORMATION_MESSAGE); //display final order      
           
            
            
    try{
        String txt3 = ("Customer information: ") ;       
        String txt =  ("\n Name: " + nameT.getText());
        String txt2 = ("\n Address: " + address.getText());   
        String txt4 = ("\n City: " + city.getText());
        String txt5 = ("\n State: " + state.getText());
        String txt6 = ("\n ZIP: " + zipT.getText());           //Initialize strings with messages
        String txt7 = ("\n Phone #: " + phoneN.getText()); 
        
        String txt8 = ("\n\n Order details: ");
        String txt9 = ("\n Sandwich type: x" + quantityS.getValue() + " " + sizeS.getSelectedValue() +" " + typeS.getSelectedValue());
        String txt10= ("\n Bread: " + breadS.getSelectedValue());
        String txt11 =("\n Beverage: " + beverageS.getSelectedValue());
    
        
    File text = new File("order.txt");
    BufferedWriter fw = new BufferedWriter(new FileWriter(text));
    fw.write(txt3);
    fw.write(txt);
    fw.write(txt2);   
    fw.write(txt4);
    fw.write(txt5);
    fw.write(txt6);// write strings to txt file
    fw.write(txt7);
    fw.write(txt8);
    fw.write(txt9);
    fw.write(txt10);
    fw.write(txt11);
    
    fw.close();
    
    
    } catch (IOException e){
        
    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.INFORMATION_MESSAGE);
    }


            }
            catch (NumberFormatException nfe){
             JOptionPane.showMessageDialog(null, nfe, "Error", JOptionPane.INFORMATION_MESSAGE);    //catch and throw exceptions
            } 
              
    }//GEN-LAST:event_submitActionPerformed

    private void importFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importFActionPerformed
        // TODO add your handling code here:
        
        try{
        FileReader fr = new FileReader("order.txt"); //select file in folde4r
        String contents = "";
        int i; // initialize string and integer
        while((i = fr.read())!=-1){
            char c= (char)i;
            contents = contents + c; //read file contents and set to contents string
        }
        orderImport.setText(contents); //display file contents in text pane
      
 
        } catch (FileNotFoundException fnfe)
        {JOptionPane.showMessageDialog(null, fnfe, "Error", JOptionPane.INFORMATION_MESSAGE);    
        } catch (IOException ex) {
            Logger.getLogger(SubGUI.class.getName()).log(Level.SEVERE, null, ex); //catch errors
        }
    }//GEN-LAST:event_importFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField address;
    public javax.swing.JList<String> beverageS;
    public javax.swing.JList<String> breadS;
    public javax.swing.JTextField city;
    public javax.swing.JButton importF;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel lba;
    public javax.swing.JTextField nameT;
    public javax.swing.JTextPane orderImport;
    public javax.swing.JFormattedTextField phoneN;
    public javax.swing.JSlider quantityS;
    public javax.swing.JList<String> sizeS;
    public javax.swing.JTextField state;
    public javax.swing.JButton submit;
    public javax.swing.JList<String> typeS;
    public javax.swing.JTextField zipT;
    // End of variables declaration//GEN-END:variables

}